#!/usr/bin/env bash
# listar diretórios, selecionar e ir para diretório, criando uma nova
# sessão no tmux. Também possível ir para sessão já aberta.

main(){
	local selected=''
	local IFS=$'\n'
	lista=($(fd . ~ -t d --min-depth=1 --max-depth=8))
	lista+=($(ls -d ~/.config/*/))
	lista+=($(ls -d ~/.local/share/*/))
	lista+=($(tmux ls | cut -d: -f1)) # session allready open
	selected=$(printf '%s\n' "${lista[@]}" | fzf)

	local selected_name=$(basename "$selected")
	local tmux_running=$(pgrep tmux)

	# Caso não tenha escolhido nunhuma opção, encerrar o script
	# Caso não tenha TMUX rodando, encerrar o script
	if [[ -z "$selected" || -z "$TMUX" || -z "$tmux_running" ]]; then # -z: true para string com length zero
		exit 0
	fi

	if ! tmux has-session -t "$selected_name" 2> /dev/null; then
		if [[ -d "$selected" ]]; then
			tmux new -d -s "$selected_name" -c "$selected" -n main
		else
			exit 0
		fi
	fi

	tmux switch-client -t "$selected_name"
}

main

