#!/usr/bin/env bash
# Script para avisar quando a fonte desconectar ou parar de carregar
# TODO - Fazer um algoritmo em C

while true; do
	if [[ $(< /sys/class/power_supply/BAT0/status) == Discharging ]]; then
		notify-send -u critical -t 2000 "Aviso!" "Fonte está DESCONECTADA!"
	fi
	sleep 1
done
