#!/usr/bin/env bash
# TODO - Modo: Shuffle (comando "shuf"), repeat
# Utiliza os programas SoX e FFMpeg, fonte Google Source Code Pro Medium
# Dmenu_flac cria um menu interativo para busca e interação básica com arquivos de música (dentro da pasta ~/Música/).
# Músicas que tenham o mesmo nome irão entrar em conflito (comando "find"), não tocando nenhuma delas - SOLUÇÃO renomear de forma diferente
# Troca do comando "cat" para o comando "grep --color=never . ". Troca do comando "grep --color=never ." por "<"

DMENU_PASTA="$HOME/.local/share/dmenu_flac"
MUSICAS_PASTA="$HOME/Música/"

# Arquivos usados
arq_lista_de_musicas="$DMENU_PASTA/lista_de_musicas_completa.dmenu"
arq_indice="$DMENU_PASTA/indice_playlist.dmenu"
arq_modulo="$DMENU_PASTA/modulo.dmenu"
arq_pastas_musicas="$DMENU_PASTA/pastas_de_musicas.dmenu"

# Programa usado para tocar as músicas (Faz parte do pacote SoX)
programaFLAC=play
programaMP3=ffplay

# Keys
KEY_DMENU_FLAC_PLAY=p
KEY_DMENU_FLAC_STOP=s
KEY_DMENU_FLAC_KILL_MUSIC=x
KEY_DMENU_FLAC_NEXT=n
KEY_DMENU_FLAC_PREVIOUS=b
KEY_DMENU_FLAC_QUIT_PLAYLIST=q

# Fonte dmenu
FONT_DMENU="Source Code Pro Medium"
FONT_DMENU_FOREGROUND=#d7d7d7
FONT_DMENU_BACKGROUND=#080808

# Função que atualiza o arquivo das músicas
atualizar_listas_de_musicas() {
	# Captura todas as músicas nos formatos flac, ogg, mp3
	sort -R < <(du -a "$MUSICAS_PASTA" | cut -f2 | grep --color=never ".flac\|.mp3\|.ogg") > "$arq_lista_de_musicas" &&
	# Captura todas as pastas dentro da pasta ~/Música/
	du -a "$MUSICAS_PASTA" | cut -f2 | grep --color=never -v "\/.*\..*$" | sed "/\/$/d" > "$arq_pastas_musicas"
}

atualizar_statusbar(){
	sleep 1
	pkill -fx "sleep 1m" &
}

player() {
	[[ $id_musica != '' ]] && kill "$id_musica"
		
	# Dar update no statusbar
	atualizar_statusbar
	if [[ $1 != *.mp3 ]]; then
		play "$1"
	else
		ffplay -loglevel quiet -nodisp -autoexit "$1"
	fi
}

tocar_musica() {
	# Utiliza Dmenu para abrir um arquivo individualmente
	# Registrando módulo
	echo '1' > "$arq_modulo"
	# Sempre observar a necessidade de usar IFS (valor padrão <space><tab><newline>) quando criar listas de comandos
	IFS=$'\n'
	# Captura os nomes das músicas para uso do Dmenu, podemos usar "|" para não precisar "escapar" "/"
	local todas_musicas=($(sed "s|^.*/\(.*\)$|\1|g" "$arq_lista_de_musicas"))
	# Captura música
	local musica_escolhida=$(printf '%s\n' "${todas_musicas[@]}" | dmenu -p "Escolha uma música:" -b -i -f -l "$linhas" -fn "$FONT_DMENU" -nb "$FONT_DMENU_BACKGROUND" -nf "$FONT_DMENU_FOREGROUND" -sb "$FONT_DMENU_FOREGROUND" -sf "$FONT_DMENU_BACKGROUND")
	# Busca exatamente pela full path da musica
	local musica=$(grep --color=never "$musica_escolhida$" "$arq_lista_de_musicas")
	player "$musica"
	atualizar_statusbar
}

tocar_playlist() {
	# Abrindo Dmenu com opções de "playlist", sendo estas as pastas dentro de Música/
	# Registrando módulo
	echo '2' > "$arq_modulo"
	IFS=$'\n'
	# Obtendo array com os nomes das pastas
	local pastas=($(sed "s|.*/\(.*\)$|\1|g" "$arq_pastas_musicas"))
	# Dmenu
	local escolher_playlist=$(printf '%s\n' "${pastas[@]}" | dmenu -p "Escolha uma das opçoes:" -b -i -f -l "$linhas" -fn "$FONT_DMENU" -nb "$FONT_DMENU_BACKGROUND" -nf "$FONT_DMENU_FOREGROUND" -sb "$FONT_DMENU_FOREGROUND" -sf "$FONT_DMENU_BACKGROUND")
	[[ $escolher_playlist != '' ]] && notify-send -t 3250 "DMENU_FLAC" "Tocando: $escolher_playlist"
	# Encontrar o endereço da pasta escolhida
	local caminho_completo_pasta=$(grep --color=never "$escolher_playlist$" "$arq_pastas_musicas")
	local musicas_da_pasta=($(ls "$caminho_completo_pasta"/*.{ogg,flac,mp3} 2> /dev/null))
	# Inicia o índice do array com o valor "0"
	echo '0' > "$arq_indice"
	while [[ $(< "$arq_indice") -lt ${#musicas_da_pasta[@]} ]]; do
		player "${musicas_da_pasta["$(< "$arq_indice")"]}"
		# Atualiza indice no "arq_indice"
		echo "$(($(< "$arq_indice") + 1))" > "$arq_indice"
	done
	atualizar_statusbar
}

proxima_musica() {
	pkill -f "ffplay|play" &
	atualizar_statusbar
}

musica_anterior() {
	# O que acontece quando o índice é negativo? Como em Python, assumem valores no final do array, sentido contrário
	# printf "formato" aceita somente números naturais
	echo "$(($(< "$arq_indice") - 2))" > "$arq_indice"
	proxima_musica
}

eliminar_playlist(){
	proxima_musica
	pkill -fx "bash.*/dmenu_flac" &
}

# Criando arquivo que conterá todas as músicas da pasta /home/andre/Música - Primeira operação realizada
[[ ! -e "$arq_lista_de_musicas" ]] && atualizar_listas_de_musicas
	
# Mostra título da música no Dmenu
musica_tocando=$(pgrep -a "$programaFLAC" | sed "s|.*/\(.*\)$|Playing: \"\1\"|g")

# Identifica corretamente o ID do processo que pertence à música
id_musica=$(pgrep -f "ffplay|play")

# Opções do Dmenu
if [[ $(pgrep "ffplay|play") == '' ]]; then
	menu_dmenu=("[1] - [Procurar por Música]" "[2] - [Escolher por Músicas por Pasta]" "[3] - [Atualizar lista de Músicas]")
else
	# Dmenu's diferentes para "playlist" e música "solo"
	case "$(< "$arq_modulo")" in
		1)menu_dmenu=("[$KEY_DMENU_FLAC_PLAY] - [Play!]" "[$KEY_DMENU_FLAC_STOP] - [Stop!]" "[$KEY_DMENU_FLAC_KILL_MUSIC] - [Parar Música!]" "[] - [$musica_tocando]");;
		*)menu_dmenu=("[$KEY_DMENU_FLAC_PLAY] - [Play!]" "[$KEY_DMENU_FLAC_STOP] - [Stop!]" "[$KEY_DMENU_FLAC_NEXT] - [Próxima Música!]" "[$KEY_DMENU_FLAC_PREVIOUS] - [Música Anterior!]" "[$KEY_DMENU_FLAC_QUIT_PLAYLIST] - [Encerrar Playlist!]" "[] - [$musica_tocando]");;
	esac
fi

# Número de "entradas" do menu - Dmenu
if [[ ${#menu_dmenu[@]} -lt 5 ]]; then
	linhas=5
else
	linhas="${#menu_dmenu[@]}"
fi

# Praticamente o menu que aparece para o usuário, capturando a ação desejada
main_menu=$(printf '%s\n' "${menu_dmenu[@]}" | dmenu -p "Escolha uma das opçoes:" -b -i -f -l "$linhas" -fn "$FONT_DMENU" -nb "$FONT_DMENU_BACKGROUND" -nf "$FONT_DMENU_FOREGROUND" -sb "$FONT_DMENU_FOREGROUND" -sf "$FONT_DMENU_BACKGROUND")

# Controle das ações do dmenu_flac
case "${main_menu:1:1}" in
	# Procurar Música
	1) tocar_musica;;
	# Tocar Músicas de Pasta
	2) tocar_playlist;;
	# Atualizar Lista de Músicas
	3) atualizar_listas_de_musicas;;
	# Play
	$KEY_DMENU_FLAC_PLAY) kill -cont "$id_musica";;
	# Stop
	$KEY_DMENU_FLAC_STOP) kill -stop "$id_musica";;
	# Encerra playlist
	$KEY_DMENU_FLAC_QUIT_PLAYLIST) eliminar_playlist;;
	# Next/Eliminar a música atual
	$KEY_DMENU_FLAC_KILL_MUSIC|$KEY_DMENU_FLAC_NEXT) proxima_musica;;
	# Previous
	$KEY_DMENU_FLAC_PREVIOUS) musica_anterior;;
esac
