#!/usr/bin/env bash
# TODO - Fazer com que o script não rode caso tenha mesmo script já rodando

#SEPARADOR=''
SEPARADOR='|'

music_playing() {
	DWM_MOSTRAR_MUSICA=$(pgrep -a "mplayer|ffplay|paplay")
	[[ $DWM_MOSTRAR_MUSICA != '' ]] && DWM_MOSTRAR_MUSICA="$SEPARADOR  ${DWM_MOSTRAR_MUSICA##*/} "
}

date_hour() {
	DWM_MOSTRAR_DATA="$SEPARADOR $(date '+%d/%b %H:%M') $SEPARADOR"
}

volume_system() {
	DWM_MOSTRAR_VOLUME="$SEPARADOR Vol: $(pactl list sinks | sed -n "10s/[\ ]//gp" | cut -d'/' -f2) "
	#DWM_MOSTRAR_VOLUME="$SEPARADOR Vol: $(< "$HOME/.vol_mon.volume")% "
}

hd_usage(){
	DWM_MOSTRAR_USO_HD="$SEPARADOR HD: $(df -h --output=avail | sed -n "4s/[\ ]//gp") "
}

while true; do
	music_playing
	volume_system
	date_hour
	hd_usage
	xsetroot -name "$DWM_MOSTRAR_MUSICA$DWM_MOSTRAR_VOLUME$DWM_MOSTRAR_USO_HD$DWM_MOSTRAR_DATA"
	sleep 1m
done &
