#!/usr/bin/env bash

# Script player para arquivos de audio

MUSICA="$1"
PLAY=(mplayer -really-quiet)
ID_MUS=$(pgrep -f "^$PLAY")

# Dar update no statusbar
atualizar_statusbar(){
	"$HOME"/.config/lemonbar/run_lemonbar &
}

play_music(){
	atualizar_statusbar
	"${PLAY[@]}" "$MUSICA"
}

main(){
	[[ $ID_MUS != '' ]] && kill "$ID_MUS"
	play_music
	atualizar_statusbar
}

main
