#!/usr/bin/env bash

# TODO - Criar um script para fazer download automático de subtitles

# Script para abrir arquivos de vídeo com subtítulos usando ffmpeg

VIDEO="$1"
ARQUIVO_SRT="${1/${1##*.}/srt}"
ARQUIVO_TEMP="${1%/*}"/temp.srt
PLAY=(ffplay -loglevel quiet -autoexit -i)

# Atualiza o status bar
atualizar_statusbar(){
	"$HOME"/.config/lemonbar/run_lemonbar &
}

# $1=$ARQUIVO_SRT; $2=$ARQUIVO_TEMP
# Verifica a codificação do arquivo .srt e converter para UTF-8
to_utf8(){
	PLAY+=(-vf subtitles="$1")
	local char_code=$(chardet3 "$1" | sed "s/^.*:\ //g" | cut -d' ' -f1)

	if [[ $char_code != utf-8 ]]
	then
	   iconv -f "$char_code" -t UTF-8 "$1" -o "$2"
	   [[ -e $2 ]] && rm "$1" && mv "$2" "$1"
	fi
}

play_video(){
	atualizar_statusbar
	# Problema com espaço? Sim, comandos que precisam interpretar "espaço" ou outros caracteres precisam ser "quotados"
	"${PLAY[@]}" "$VIDEO"
}

main(){
	# Verificar se arquivo srt existe, caso contrário, rodar o vídeo sem
	if [[ ! -e $ARQUIVO_SRT ]]
	then
		play_video
	else
		to_utf8 "$ARQUIVO_SRT" "$ARQUIVO_TEMP"
		play_video
	fi
	atualizar_statusbar
}

main
