#!/usr/bin/env bash

processo_existe(){
	[[ $(pidof -sx "$1") ]] || [[ $(pgrep -f "$1" ) ]] 
	echo $?
}

DMENU_OPCOES=("GravaçãoYoutube" "GravaçãoTela" "EncerrarGravação")

# variável de acordo com DMENU_OPCOES
LINHAS="${#DMENU_OPCOES[@]}"

OPCAO_ESCOLHIDA=$(printf '%s\n' "${DMENU_OPCOES[@]}" | dmenu $* -p "Escolha uma das opçoes:" -b -i -f -l "$LINHAS" -fn "Source Code Pro Medium" -nb "#080808" -nf "#d7d7d7" -sb "#d7d7d7" -sf "#080808")

# Acho que a opção "-vf" pode ser retirada
# Codec de audio precisa ser "aac" para o output do video "flv"
if [[ -n $DMENU_OPCOES ]]
then
	case "$OPCAO_ESCOLHIDA" in
	#IniciarGravaçãoYoutube)ffmpeg -f alsa -i default -f x11grab -framerate 30 -video_size "$(xdpyinfo | grep dimensions | awk '{print $2}')" -i :0.0+0,0 -c:v libx264 -preset veryfast -maxrate 1984k -bufsize 3968k -vf "format=yuv420p" -g 60 -c:a aac -b:a 128k -ar 44100 -f flv rtmp://a.rtmp.youtube.com/live2/"$stream_key";;
		(GravaçãoYoutube)
			stream_key=$(zenity --entry --title="StreamKey YouTube" --text="Insira StreamKey do YouTube (Ou pressione ENTER para CONTINUAR):")
			ffmpeg -f x11grab -s "$(xdpyinfo | grep dimensions | awk '{print $2}')" -i "$DISPLAY" -f alsa -i default -ar 44100 -c:v libx264 -r 30 -c:a aac -f flv rtmp://a.rtmp.youtube.com/live2/"$stream_key";;
		(GravaçãoTela)
			if [[ $(processo_existe "ffmpeg") != 0 ]]
			then
				notify-send -t 5000 "Gravação inicializada!"
				ffmpeg -y -f x11grab -s "$(xdpyinfo | grep dimensions | awk '{print $2}')" -i "$DISPLAY" -f alsa -i default -ar 44100 -c:v libx264 -r 30 -c:a aac "$HOME"/output_FFMPEG.mkv
			fi;;
		(EncerrarGravação)
			pkill ffmpeg
			notify-send -t 5000 "Gravação finalizada!";;
	esac
fi
