#!/usr/bin/env bash
# script para listar e instalar packages do archive.archlinux,
# principalmente para downgrade

init(){
	# Inicializa variáveis do script
	ARCHIVE="https://archive.artixlinux.org/packages/"
	ARCHIVE2="https://archive2.artixlinux.org/packages/"
}

# lista packages já instalados
# input deve ser como o nome do package em pacman
baixados(){
	ls /var/cache/pacman/pkg/* | grep --color=never "$1"
}

instalar(){
	local programa="${1%-[0-9.]*-[0-9]-*}"
	sudo pacman -U "${ARCHIVE}${programa::1}/${programa}/${1}"
}

# lista packages disponíveis em archive.archlinux
# input deve ser como o nome do package em pacman
listar(){
	if pacman -Ss "${1}" 1> /dev/null
	then
		curl -s "${ARCHIVE}${1::1}/${1}/" | sed -n "s/^.*>\(.*\)<.*$/\1/p" | grep --color=never -e "zst$"
	fi
}

ajuda(){
	local msg=(
	"Comandos:" \
	"list <pkg>			liste os pacotes com nome <pkg>" \
	"install <pkg>			realiza a instalação do <pkg>"
	)
	printf '%s\n' "${msg[@]}"
}

sair(){
	echo "$1: comando não listado." 
	ajuda
	exit $2
}

main(){
	init
	case "$1" in
		(-l|--list)
			# nome dos packages do pacman
			shift
			if (( $# > 1 ))
			then
				sair "$1" 1
			fi
			listar "$1"
			;;
		(-i|--install)
			# input no formato listado no comando 'list'
			shift
			if (( $# == 1 ))
			then
				instalar "$1"
			else
				ajuda
				exit 0
			fi
			;;
		(-c|--cached)
			shift
			baixados "$1"
			;;
		(-h|--help)
			echo "WIP"
			;;
		(*)
			sair "$1" 0
			;;
	esac
}

main "$@"
