#!/usr/bin/env bash

#zenity --password
# printf 'Digite sua senha sudo:\n' | dmenu -l 1 -fn "Source Code Pro Medium"
echo '' | tofi --width=300 --height=100 --require-match=false --placeholder-text="Insira senha sudo" 2> /dev/null
