#!/usr/bin/env bash

main(){
	local selected=''
	if [[ $# -eq 1 ]]; then
		selected=$1
	else
		lista=($(find ~/git -mindepth 1 -maxdepth 1 -type d))
		lista+=($(tmux ls | cut -d: -f1))
		selected=$(printf '%s\n' "${lista[@]}" | fzf)
	fi

	# Caso não tenha escolhido nunhuma opção, encerrar o script
	if [[ -z $selected ]]; then # -z: true para string com length zero
		exit 0
	fi

	local selected_name=$(basename "$selected" | tr . _)
	local tmux_running=$(pgrep tmux)

	if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
		if [[ -d $selected ]]; then
			tmux new-session -s $selected_name -c $selected
			exit 0
		else
			tmux new-session -s $selected_name
			exit 0
		fi
	fi

	if ! tmux has-session -t=$selected_name 2> /dev/null; then
		if [[ -d $selected ]]; then
			tmux new-session -ds $selected_name -c $selected
		else
			tmux new-session -ds $selected_name
		fi
	fi

	tmux switch-client -t $selected_name
}

main

