#!/usr/bin/env bash
# Script para tirar screenshot da tela

nome_arquivo="$(zenity --entry --title="ScreenShot!" --text="Insira o nome do arquivo:").png"

import -window root "$HOME/Imagens/screenshot/$nome_arquivo"
