#!/usr/bin/env bash

main(){
	local IFS=$'\n'
	CACHE_DIR=${XDG_CACHE_HOME:="$HOME/.cache"}
	if [[ ! -e $CACHE_DIR/wofi_run ]]
	then
		dmenu_path > "$CACHE_DIR/wofi_run"
	fi
	WOFI_COMMAND_LIST=$(< "$CACHE_DIR/wofi_run")
	printf '%s\n' "$WOFI_COMMAND_LIST" | wofi --show dmenu | ${SHELL:-"/bin/bash"}
}

main

