#!/usr/bin/env bash
#Script para download de videos do youtube
#TODO - --hls-prefer-ffmpeg 

link=$(zenity --entry --title="Youtube-Video" --text="Insira o link para download do video")

id_link=$(youtube-dl --get-id "$link")

nome_arquivo=$(youtube-dl --get-title "$link")

youtube-dl -q --no-playlist --hls-prefer-native -f "[height<=720]" -o "$HOME/Videos/%(id)s.%(ext)s" "$link"  
#youtube-dl -q --no-playlist -f "[height<=720]" -o "$HOME/Videos/%(id)s.%(ext)s" "$link"  

nome_atual_arquivo=$(ls "$HOME/Videos" | grep --color=never "$id_link")

if [[ -e $HOME/Videos/$nome_atual_arquivo ]]; then
	notify-send --expire-time=3250 "Youtube-Video" "Vídeo $nome_arquivo concluído com sucesso"
	mv "$HOME/Videos/$nome_atual_arquivo" "$HOME/Videos/$nome_arquivo.${nome_atual_arquivo//*./}"
else
	notify-send --expire-time=3250 -u critical "Youtube-Video" "Vídeo $nome_arquivo NÃO concluído com sucesso"
fi
