#!/usr/bin/env bash
# Script que utiliza os pacotes youtube-dl e ffmpeg para baixar audio do YouTube e converter esse nome_arquivo para o formato OGG

erro_abortar(){
   notify-send -u critical --expire-time=3250 "YouTube-Flac" "Áudio: $nome_arquivo - Falhou..."
}

sucesso(){
   notify-send --expire-time=3250 "YouTube-Flac" "Áudio: $nome_arquivo - Concluído com Sucesso!"
}

trap erro_abortar EXIT

set -e

# Adicionar mais caracteres que não são interpretados pelo comando "mv"
caracter_proibido='\/'

link=$(zenity --entry --title="YouTube-FLAC" --text="Para download e conversão de áudio do YouTube, insira o link")

nome_arquivo=$(youtube-dl --get-title "$link")

id_link=$(youtube-dl --get-id "$link")

youtube-dl -q --no-playlist --youtube-skip-dash-manifest -f bestaudio -o "$HOME/Música/AudiosYouTube/%(id)s.%(ext)s" "$link"

nome_atual_arquivo=$(ls "$HOME/Música/AudiosYouTube" | grep --color=never "$id_link")

ffmpeg -i "$HOME/Música/AudiosYouTube/$nome_atual_arquivo" "$HOME/Música/AudiosYouTube/${nome_arquivo//["$caracter_proibido"]/}.ogg" -loglevel quiet

if [[ -e $HOME/Música/AudiosYouTube/$nome_atual_arquivo ]]; then
   rm "$HOME/Música/AudiosYouTube/$nome_atual_arquivo"
fi

trap sucesso EXIT
