#!/usr/bin/env bash

# TODO - Refazer todo o script de forma coerente!!!!!

# Script que utiliza os pacotes youtube-dl e ffmpeg para baixar audio/video do YouTube 

init_variables(){
	NOME_SCRIPT="${1##*/}"
	# Adicionar mais caracteres que não são interpretados pelo comando "mv"
	CARACTER_PROIBIDO='\/' 
	NOTIFY_TIME=7000
	PASTA_MUSICA="$HOME/documents/music/AUDIO_DOWNLOADS"
	PASTA_VIDEO="$HOME/documents/videos"
}

run_ffmpeg(){
	local FFMPEG_COMMAND=(ffmpeg -loglevel quiet -i "$ARQUIVO_TEMP" -q:a 5 "$PASTA_MUSICA/${ARQUIVO_FINAL//[$CARACTER_PROIBIDO]/}".ogg)
	"${FFMPEG_COMMAND[@]}"
}

run_command_audio(){
	local DOWNLOAD_AUDIO=(youtube-dl -q --no-playlist --youtube-skip-dash-manifest --socket-timeout 60 -f "bestaudio" -o "$PASTA_MUSICA/temp_%(id)s.%(ext)s" "$LINK")
	"${DOWNLOAD_AUDIO[@]}"
	ARQUIVO_TEMP=$(ls "$PASTA_MUSICA/$ARQUIVO_TEMP".*)
	run_ffmpeg
	final_operation "audio"
}

run_command_video(){
	local DOWNLOAD_VIDEO=(youtube-dl -q --no-playlist --youtube-skip-dash-manifest --socket-timeout 60 --hls-prefer-native -f "[height<=720]" -o "$PASTA_VIDEO/temp_%(id)s.%(ext)s" "$LINK")
	"${DOWNLOAD_VIDEO[@]}"
	ARQUIVO_TEMP=$(ls "$PASTA_VIDEO/$ARQUIVO_TEMP".*)
	final_operation "video"
}

run_dmenu_command(){
	dmenu -i -f -l "$MENU_DMENU_LINES" -fn "Source Code Pro Medium:size=14"
}

# $1=LINK $2=ARQUIVO_FINAL $3=ARQUIVO_TEMP
selecting_variables(){
	if [[ $1 != '' ]]
	then
		LINK="$1"
	else
		LINK=$(xsel -o -b)
	fi
	if [[ $2 != '' ]] 
	then
		ARQUIVO_FINAL="$2"
	else
		ARQUIVO_FINAL=$(youtube-dl --no-playlist --youtube-skip-dash-manifest --socket-timeout 60 --get-title "$LINK") 
	fi
	if [[ $3 != '' ]] 
	then
		ARQUIVO_TEMP="$3"
	else
		ARQUIVO_TEMP=temp_"$(youtube-dl --no-playlist --youtube-skip-dash-manifest --socket-timeout 60 --get-id "$LINK")" 
	fi
}

remove_temp_file(){
	[[ -e $ARQUIVO_TEMP ]] && rm "$ARQUIVO_TEMP"
}

rename_file(){
	[[ -e $ARQUIVO_TEMP ]] && mv "$ARQUIVO_TEMP" "$PASTA_VIDEO/${ARQUIVO_FINAL//[$CARACTER_PROIBIDO]/}.${ARQUIVO_TEMP##*.}"
}

try_again_if_error(){
	((FLAC_LEVEL++))
	[[ $FLAC_LEVEL -lt 5 ]] && "$NOME_SCRIPT" "$LINK" "$ARQUIVO_FINAL" "$ARQUIVO_TEMP"
}

final_operation(){
	case "$1" in
		(audio)
			remove_temp_file;;
		(video)
			rename_file;;
	esac
}

choosing_audio_or_video(){
	case "${OPTION:1:1}" in
		(1)
			run_command_audio;;
		(2)
			run_command_video;;
	esac
}

# Definindo variáveis para download
downloading(){
	local ESCOLHER_DOWNLOAD=("[1] Baixar audio" "[2] Baixar video")
	MENU_DMENU_LINES=$((${#ESCOLHER_DOWNLOAD[@]} + 1))
	OPTION=$(printf "%s\n" "Escolha uma das opções:" "${ESCOLHER_DOWNLOAD[@]}" | run_dmenu_command)
	# $1=LINK $2=ARQUIVO_FINAL $3=ARQUIVO_TEMP
	selecting_variables "$1" "$2" "$3"
	choosing_audio_or_video
}

error_abort(){
	notify-send -u critical -t "$NOTIFY_TIME" "ERRO!" "Arquivo: $ARQUIVO_FINAL - Falhou... $ERROR_MESSAGE"
	# Remover o arquivo temp
	final_operation "audio"
	# Melhorar como irá acontecer a recursão
	try_again_if_error
}

sucess(){
	notify-send -t "$NOTIFY_TIME" "SUCESSO!" "Arquivo: $ARQUIVO_FINAL - Concluído com Sucesso!"
}

main(){
	trap error_abort EXIT
	set -e
	# Shell Level para controlar método "try_again_if_error"
	FLAC_LEVEL=
	init_variables "$0"
	downloading "$1" "$2" "$3"
	trap sucess EXIT
}

main "$@"
