#!/usr/bin/env bash
# TODO -

separador=' '

music_playing() {
	if [[ $(pgrep play) == '' ]]; then
		mostrar_musica=''
	else
		mostrar_musica=$separador$(pgrep -a play | sed "s/^.*\/\(.*\)$/ \1 /g")
	fi
}

date_hour() {
	mostrar_data=$separador$(date '+%d/%b %H:%M ')$separador
}

volume_system() {
	mostrar_volume=$separador$(pactl list sinks | grep --color=never "Volume: " | awk '{print $5}' | sed "s/^\(.*\)$/Vol: \1 /g")
}

hd_usage(){
	mostrar_uso_hd=$separador$(df -h | grep --color=never "sda6" | awk '{print $4}' | sed "s/^\(.*\)$/HD:\1 /g")
}

# Comando é lento quando atualiza status
#wifi_display() {
#	mostrar_wifi="WiFi [off]"
#	if [[ $(nmcli dev | grep wifi | awk '{print $3}') != desconectado ]]; then
#		mostrar_wifi="WiFi ["$(nmcli connection show --active | grep wifi | awk '{print $1}')"]"
#	fi
#}

while true; do
	music_playing
	volume_system
	date_hour
	hd_usage
#	wifi_display
	xsetroot -name "$mostrar_musica$mostrar_volume$mostrar_uso_hd$mostrar_data"
	sleep 1m
done
