#!/bin/bash

while true; do
	if [[ $(acpi -b | sed	"s/^.*\(Discharging\|Charging\).*$/\1/") == Discharging ]]; then
		notify-send -u critical -t 10000 "Fonte está DESCONECTADA!"
		sleep 10
	fi
	sleep 1
done
