#!/usr/bin/env bash
# Utiliza os programas SoX e FFMpeg
# Dmenu_flac cria um menu interativo para busca e interação básica com música (e audio em geral) que estão armazanados no computador.

lista_de_musicas="$HOME"/.local/share/listas_musicas.txt

[[ ! -e "$lista_de_musicas" ]] && {
	(find "$HOME"/Música/ -name *.flac > "$lista_de_musicas" && find "$HOME"/Música/ -name *.mp3 >> "$lista_de_musicas")
}
	
# Programa usado para tocar as músicas (Faz parte do pacote SoX)
programaFLAC=play
programaMP3=ffplay

# Número de "entradas" do menu - Dmenu
linhas=6

# Mostra título da música no Dmenu
song=$(ps -q "$(pidof "$programaFLAC")" -o cmd= | sed "s/^.*\/\(.*\)$/Playing: \"\1\"/")
if [[ $song == '' ]]; then
	song=$(ps -q "$(pidof "$programaMP3")" -o cmd= | sed "s/^.*\/\(.*\) \-log.*$/Playing \"\1\"/")
fi

# IMPLEMENTAR: NEXT, PREVIOUS, SHUFFLE, REPEAT, PLAYLIST?
# Melhorar forma como as opções são disponibilizadas (usar "case")
action=$(printf '%s\n%s\n%s\n%s\n%s\n%s' "Play" "Pause" "ProcurarMúsica" "EncerrarMúsica" "AtualizarMúsicas" "$song" | dmenu $* -p "Escolha uma das opçoes:" -b -i -f -l "$linhas" -fn "Source Code Pro Medium" -nb "#080808" -nf "#d7d7d7" -sb "#d7d7d7" -sf "#080808")

# Identifica corretamente o ID do processo que pertence à música
id_flac=$(pidof "$programaFLAC")
if [[ $id_flac == '' ]]; then
	id_flac=$(pidof "$programaMP3")
fi

abrir_arquivo() {
	# Utiliza Dmenu para abrir um arquivo individualmente

	# Cria um array "arquivos" passando as linhas do arquivo como variáveis
	mapfile -t arquivos < "$lista_de_musicas"
	# Captura os nomes das músicas para uso do Dmenu
	nome_arquivos+=("$(sed "s/^.*\/\(.*\)$/\1/g" "$lista_de_musicas")")
	# Captura música
	nome_escolhido_arquivo=$(printf '%s\n' "${nome_arquivos[@]}" | dmenu $* -p "Escolha uma música:" -b -i -f -l "$linhas" -fn "Source Code Pro Medium" -nb "#080808" -nf "#d7d7d7" -sb "#d7d7d7" -sf "#080808")

	# Busca exatamente pelo "pattern" passado
	caminho_completo=$(find "$HOME"/Música/ -name "$nome_escolhido_arquivo")
	if [[ $nome_escolhido_arquivo != *.mp3 ]]; then
		play "$caminho_completo"
	else
		ffplay "$caminho_completo" -loglevel quiet -nodisp -autoexit
	fi
}

case "$action" in
	ProcurarMúsica) abrir_arquivo;;
	Play) kill -cont "$id_flac";;
	Pause) kill -stop "$id_flac";;
	AtualizarMúsicas)(find "$HOME"/Música/ -name *.flac > "$lista_de_musicas" && find "$HOME"/Música/ -name *.mp3 >> "$lista_de_musicas");;
	EncerrarMúsica) pkill "$programaFLAC";;
esac

# Comandos desatualizados (Código descartado)
#SONG=$(ps a -o pid,command | grep /usr/bin/play | tr '\n' ' ' | sed "s/^.*\/\(.*\) [[:digit:]].*$/\1/g")


#if [[ $? != 0 ]]; then
#	pkill "$programaMP3"
#fi

# Comando trocado por "sed" (MUITO mais rápido!)
#for arquivo in "${arquivos[@]}"; do
#	nome_arquivos+=("$(printf '%s\n' "$arquivo" | sed "s/^.*\/\(.*\)$/\1/g")")
#done


#for arquivo in "${arquivos[@]}"; do
#	if [[  $nome_escolhido_arquivo == $(printf '%s\n' "$arquivo" | sed "s/^.*\/\(.*\)$/\1/g") ]]; then
#		caminho_completo="$arquivo"
#		break
#	fi
#done

#if [[ $action == ProcurarMúsica ]]; then
#	abrir_arquivo
#fi
#
#if [[ $action == Play ]]; then
#	kill -CONT "$id_flac"
#fi
#
#if [[ $action == Pause ]]; then
#	kill -STOP "$id_flac"
#fi
#
#if [[ $action == EncerrarMúsica ]]; then
#	# Não importa qual programa é, pkill play mata os dois tipos de processo
#	pkill "$programaFLAC"
#fi
